export const Category = [
  "Technology News",
  "HotPost",
  "Featured",
  "Programming",
  "Web Development",
  "Mobile Apps",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Blockchain",
  "Cybersecurity",
  "Cloud Computing",
  "Internet of Things",
  "Tech Reviews",
  "Software Development",
  "Virtual Reality",
  "Robotics",
  "Hardware",
  "Networking",
  "Databases",
  "Operating Systems",
  "DevOps",
  "Linux",
];
