import { IconBaseProps, IconType } from 'react-icons';
import {
  TbAlignCenter,
  TbAlignJustified,
  TbAlignLeft,
  TbAlignRight,
  TbAlt,
  TbArrowBackUp,
  TbArrowForwardUp,
  TbBan,
  TbBold,
  TbBrandYoutube,
  TbCheck,
  TbChevronDown,
  TbClipboard,
  TbCode,
  TbDownload,
  TbEdit,
  TbEraser,
  TbExternalLink,
  TbIndentDecrease,
  TbIndentIncrease,
  TbItalic,
  TbLetterCase,
  TbLink,
  TbLinkOff,
  TbList,
  TbListDetails,
  TbListNumbers,
  TbMaximize,
  TbMinimize,
  TbMinus,
  TbPalette,
  TbPaletteOff,
  TbPhoto,
  TbPlus,
  TbRuler,
  TbSourceCode,
  TbStrikethrough,
  TbSubscript,
  TbSuperscript,
  TbTextCaption,
  TbTrash,
  TbUnderline,
  TbX,
} from 'react-icons/tb';

import IconCorner from './Corner';
import IconInlineCode from './InlineCode';
import IconQuote from './Quote';
import IconTextColor from './TextColor';
import IconTextHighlight from './TextHighlight';

export const icons = {
  Bold: TbBold,
  Italic: TbItalic,
  Underline: TbUnderline,
  Strike: TbStrikethrough,
  Code: TbCode,
  SourceCode: TbSourceCode,
  Subscript: TbSubscript,
  Superscript: TbSuperscript,
  BulletList: TbList,
  OrderedList: TbListNumbers,
  TaskList: TbListDetails,
  CodeBlock: TbCode,
  CodeInline: IconInlineCode,
  Link: TbLink,
  Unlink: TbLinkOff,
  Edit: TbEdit,
  ExternalLink: TbExternalLink,
  Redo: TbArrowForwardUp,
  Undo: TbArrowBackUp,
  AlignLeft: TbAlignLeft,
  AlignRight: TbAlignRight,
  AlignJustify: TbAlignJustified,
  AlignCenter: TbAlignCenter,
  Eraser: TbEraser,
  ChevronDown: TbChevronDown,
  Maximize: TbMaximize,
  Minimize: TbMinimize,
  HorizontalRule: TbMinus,
  Indent: TbIndentIncrease,
  Outdent: TbIndentDecrease,
  Clipboard: TbClipboard,
  Check: TbCheck,
  Quote: IconQuote,
  Corner: IconCorner,
  LetterCase: TbLetterCase,
  Trash: TbTrash,
  Image: TbPhoto,
  ImageCaption: TbTextCaption,
  ImageAltText: TbAlt,
  Download: TbDownload,
  Youtube: TbBrandYoutube,
  Close: TbX,
  Ruler: TbRuler,
  TextHighlight: IconTextHighlight,
  TextColor: IconTextColor,
  Palette: TbPalette,
  PaletteOff: TbPaletteOff,
  Ban: TbBan,
  Plus: TbPlus,
} satisfies Record<string, IconType>;

export type { IconBaseProps, IconType };
