import type { IconBaseProps, IconType } from 'react-icons';
import { AiOutlineMergeCells, AiOutlineSplitCells } from 'react-icons/ai';
import {
  TbAlignBoxBottomCenter,
  TbAlignBoxCenterMiddle,
  TbAlignBoxLeftBottom,
  TbAlignBoxLeftMiddle,
  TbAlignBoxLeftTop,
  TbAlignBoxRightBottom,
  TbAlignBoxRightMiddle,
  TbAlignBoxRightTop,
  TbAlignBoxTopCenter,
  TbAlignCenter,
  TbAlignJustified,
  TbAlignLeft,
  TbAlignRight,
  TbAlt,
  TbArrowBackUp,
  TbArrowDown,
  TbArrowForwardUp,
  TbArrowsHorizontal,
  TbArrowUp,
  TbBan,
  TbBold,
  TbBrandYoutube,
  TbCheck,
  TbChevronDown,
  TbClipboard,
  TbCode,
  TbColumnInsertLeft,
  TbColumnInsertRight,
  TbColumnRemove,
  TbCopy,
  TbDownload,
  TbEdit,
  TbEraser,
  TbExternalLink,
  TbGripVertical,
  TbIndentDecrease,
  TbIndentIncrease,
  TbItalic,
  TbLetterCase,
  TbLink,
  TbLinkOff,
  TbList,
  TbListDetails,
  TbListNumbers,
  TbMaximize,
  TbMinimize,
  TbMinus,
  TbMoodSmile,
  TbPalette,
  TbPaletteOff,
  TbPhoto,
  TbPlus,
  TbRowInsertBottom,
  TbRowInsertTop,
  TbRowRemove,
  TbRuler,
  TbScissors,
  TbSearch,
  TbSourceCode,
  TbStrikethrough,
  TbSubscript,
  TbSuperscript,
  TbTable,
  TbTableColumn,
  TbTableMinus,
  TbTablePlus,
  TbTableRow,
  TbTextCaption,
  TbTrash,
  TbUnderline,
  TbX,
} from 'react-icons/tb';

import IconCorner from './Corner';
import IconInlineCode from './InlineCode';
import IconQuote from './Quote';
import IconTextColor from './TextColor';
import IconTextHighlight from './TextHighlight';

export const icons = {
  Bold: TbBold,
  Italic: TbItalic,
  Underline: TbUnderline,
  Strike: TbStrikethrough,
  Code: TbCode,
  SourceCode: TbSourceCode,
  Subscript: TbSubscript,
  Superscript: TbSuperscript,
  BulletList: TbList,
  OrderedList: TbListNumbers,
  TaskList: TbListDetails,
  CodeBlock: TbCode,
  CodeInline: IconInlineCode,
  Link: TbLink,
  Unlink: TbLinkOff,
  Edit: TbEdit,
  ExternalLink: TbExternalLink,
  Redo: TbArrowForwardUp,
  Undo: TbArrowBackUp,
  AlignLeft: TbAlignLeft,
  AlignRight: TbAlignRight,
  AlignJustify: TbAlignJustified,
  AlignCenter: TbAlignCenter,
  Eraser: TbEraser,
  ChevronDown: TbChevronDown,
  Maximize: TbMaximize,
  Minimize: TbMinimize,
  HorizontalRule: TbMinus,
  Indent: TbIndentIncrease,
  Outdent: TbIndentDecrease,
  Clipboard: TbClipboard,
  Check: TbCheck,
  Quote: IconQuote,
  Corner: IconCorner,
  LetterCase: TbLetterCase,
  Trash: TbTrash,
  Image: TbPhoto,
  ImageCaption: TbTextCaption,
  ImageAltText: TbAlt,
  Download: TbDownload,
  Youtube: TbBrandYoutube,
  Close: TbX,
  Ruler: TbRuler,
  TextHighlight: IconTextHighlight,
  TextColor: IconTextColor,
  Palette: TbPalette,
  PaletteOff: TbPaletteOff,
  Ban: TbBan,
  Plus: TbPlus,
  Table: TbTable,
  Stretch: TbArrowsHorizontal,
  HeaderRow: TbTableRow,
  HeaderCol: TbTableColumn,
  ColInsertLeft: TbColumnInsertLeft,
  ColInsertRight: TbColumnInsertRight,
  ColRemove: TbColumnRemove,
  ColHeader: TbTableColumn,
  RowInsertTop: TbRowInsertTop,
  RowInsertBottom: TbRowInsertBottom,
  RowRemove: TbRowRemove,
  RowHeader: TbTableRow,
  MergeCell: AiOutlineMergeCells,
  SplitCell: AiOutlineSplitCells,
  GripVertical: TbGripVertical,
  TablePlus: TbTablePlus,
  TableMinus: TbTableMinus,
  AlignTop: TbAlignBoxTopCenter,
  AlignTopLeft: TbAlignBoxLeftTop,
  AlignTopRight: TbAlignBoxRightTop,
  AlignBottom: TbAlignBoxBottomCenter,
  AlignBottomLeft: TbAlignBoxLeftBottom,
  AlignMiddleRight: TbAlignBoxRightMiddle,
  AlignMiddle: TbAlignBoxCenterMiddle,
  AlignMiddleLeft: TbAlignBoxLeftMiddle,
  AlignBottomRight: TbAlignBoxRightBottom,
  ArrowUp: TbArrowUp,
  ArrowDown: TbArrowDown,
  Scissors: TbScissors,
  Copy: TbCopy,
  Emoji: TbMoodSmile,
  Search: TbSearch,
} satisfies Record<string, IconType>;

export type { IconBaseProps, IconType };
